### PR TITLE
AltayForms lib

### PR DESCRIPTION
**Pull request by naja82**
added AltayForms lib to use in Altay form plugins just by changing namespace to use that plugins into PMMP

### CODE REVIEW

**Comment by NycuRO** [comment]
I don't recommand that. Code is bullshit in my perspective.

**Comment by naja82** [comment]
@NycuRO
1. Its not my code
2. Its TuranicTeam code
3. Yes its bullshit
4. I hate Altay
5. Some essential plugins like MagicWE2, ShopMenu, more... . These plugins are very important for Survival servers but developers because of some new features using Altay we have no solution except TeaSpoon

Now @CortexPE please wait for new file I will add tomorrow

Thank you

**Comment by naja82** [comment]
@Aericio Yes, I don't see this branch. First I see that at Altay, Altay using forms-api at master branch
Sorry for This
Closing this request

**Comment by NycuRO** [comment]
Actually exist PR with Forms Api : https://github.com/pmmp/PocketMine-MP/pull/2308

**Comment by Aericio** [comment]
It hasn't been merged yet, hence why I linked that branch instead.

**Pull request closed without merging**
