### PR TITLE
Bump API

### PR DESCRIPTION
**Pull request by xXNiceAssasinl0**
Plz accept xd

### CODE REVIEW

**Comment by armagadon159753** [comment]
#186

**Comment by xXNiceAssasinl0** [comment]
Oh xD ur bad

**Comment by CortexPE** [comment]
Duplicate xd

**Comment by CortexPE** [comment]
#186 has a more stricter API Bump to ALPHA11 xd

**Comment by xXNiceAssasinl0** [comment]
xD I didn’t saw that sry

**Pull request closed without merging**
