### PR TITLE
just wondering if this would work

### PR DESCRIPTION
**Pull request by XoticRealmsOwnerandDev**
wold this make silverfish drop emerald, you can close this

### CODE REVIEW

**Comment by CortexPE** [comment]
that'd throw a syntax error

**Comment by XoticRealmsOwnerandDev** [comment]
@CortexPE  is their a way to modify the mob drops if so can you help me out

**Comment by CortexPE** [comment]
I can make you a plugin that modifies mob drops for $5

**Comment by XoticRealmsOwnerandDev** [comment]
hmm i will think about it

**Comment by CortexPE** [comment]
mk

**Pull request closed without merging**
